language: java

jdk: oraclejdk7
  
install: ""

script: mvn -B clean package

after_failure:
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.tests/target/work/data/.metadata/.log
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.tests/target/surefire-reports/*
