language: java

jdk: oraclejdk7

env: DISPLAY=:99.0

install: true

before_install:
 - sudo apt-get update
 - sudo apt-get install -qq metacity
 - sudo apt-get install libwebkit-1.0-2

before_script:
 - sh -e /etc/init.d/xvfb start
 - sleep 5 # give xvfb some time to start
 - metacity --sm-disable --replace &
 - sleep 5 # give metacity some time to start
 
script:
 - set | sort
 - mvn -B -Dbrowser=webkit clean package

after_failure:
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.tests/target/work/data/.metadata/.log
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.tests/target/surefire-reports/*
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.ui.tests/target/work/data/.metadata/.log
 - cat /home/travis/build/satyagraha/gfm_viewer/plugin.ui.tests/target/surefire-reports/*
