language: go

sudo: false

go:
  - 1.3
  - 1.4
  # - tip

cache:
  directories:
    - bower_components

before_install:
  # For coveralls
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

  # For build
  - npm install -g bower
  - make

script:
  - "if   go version | grep '1.3' > /dev/null; then godep go test -v --race; fi"
  - "if ! go version | grep '1.3' > /dev/null; then $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN -v --race; fi"
